name: Python Package

on:
    push:
      branches: [ main ]
      

jobs:
    deploy:
       runs-on: ubuntu-latest
       strategy:
         fail-fast: false
         matrix:
            python-version: [3.9]
       steps:
        - uses: actions/checkout@main
        - name: Initialize Python3.9
          uses: actions/setup-python@v3
          with:
            python-version: ${{matrix.python-version}}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt            
        - name: Check docker installed or not
          run: docker run hello-world
        - name: Push to docker hub
          uses: docker/build-push-action/@v3

